In [30]:
import numpy as np

In [2]:
np.random.randn(100, 2)[:,1]

array([-0.83952602, -2.07803244,  0.54292545,  0.08391622,  0.19783024,
       -0.86750131, -0.66955423,  0.05705998,  0.66313425, -1.52172115,
       -1.30877611,  0.75643969, -0.81653159,  0.19580969, -0.59007341,
       -0.26979456, -0.67192084,  0.1644428 ,  0.04890279, -0.03767182,
        0.20647888, -0.50767926, -0.8873736 ,  1.72460097,  0.31404649,
       -1.23587927, -1.4575494 ,  1.01191854,  0.96749189, -1.85633363,
        1.35002345, -0.56392008, -1.62425577,  0.0497654 ,  0.43287837,
       -0.87925742,  1.7614822 , -0.57629702,  0.60402179,  1.95143893,
        0.7859023 , -0.03167746, -0.41332311,  1.61274127,  0.32963349,
       -0.5167404 , -1.10963484,  0.70335643,  0.37631949, -0.12170387,
        1.08260847, -0.03621862, -1.12479262, -0.05536466,  1.68287188,
       -1.33883067, -1.79104468,  0.04767237, -0.80530032,  0.35380726,
       -0.9894574 , -0.30908276,  0.72114549, -0.34067306,  1.63871332,
       -1.63001984,  1.50075347,  0.1901534 ,  1.48721657, -0.08

In [3]:
import numpy as np

In [4]:
int(np.ceil(7/2))

4

In [5]:
i = float("inf")
print(np.log(0))

-inf


/home/snov/environments/artsim/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [6]:
A = np.zeros((10, 62388))
B = np.zeros((10, 62388))
print(np.dot(A, B.T))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
((1/62388)**20)*40

5.012319214822605e-95

In [8]:
from gensim.test.utils import common_dictionary, common_corpus
from gensim.models import LsiModel

model = LsiModel(common_corpus, id2word=common_dictionary)
vectorized_corpus = model[common_corpus]  # vectorize input copus in BoW format

In [19]:
print(list((k,v) for k,v in common_dictionary.items()), type(common_dictionary))

for cc in common_corpus:
    print(cc)


for k in common_dictionary.keys():
    print(k)

common_corpus[0]

[(0, 'computer'), (1, 'human'), (2, 'interface'), (3, 'response'), (4, 'survey'), (5, 'system'), (6, 'time'), (7, 'user'), (8, 'eps'), (9, 'trees'), (10, 'graph'), (11, 'minors')] <class 'gensim.corpora.dictionary.Dictionary'>
[(0, 1), (1, 1), (2, 1)]
[(0, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)]
[(2, 1), (5, 1), (7, 1), (8, 1)]
[(1, 1), (5, 2), (8, 1)]
[(3, 1), (6, 1), (7, 1)]
[(9, 1)]
[(9, 1), (10, 1)]
[(9, 1), (10, 1), (11, 1)]
[(4, 1), (10, 1), (11, 1)]
0
1
2
3
4
5
6
7
8
9
10
11


[(0, 1), (1, 1), (2, 1)]

In [ ]:
print(model, list(vectorized_corpus))

In [ ]:
from somhos.methods.useful import save_pickle, load_pickle
from somhos.config.paths import *

prefix_path = "../../"
data_path = get_relative_path(prefix_path, V9GAMMA_PATH)

# Load sample A
docs_sample_a = load_pickle(get_relative_path(data_path, DOCS_SAMPLE_A_SUFFIX))
# Load sample B
docs_sample_b = load_pickle(get_relative_path(data_path, DOCS_SAMPLE_B_SUFFIX))

print("Samples size: (%d, %d)" % (len(docs_sample_a), len(docs_sample_b)))

samples_content = load_pickle(get_relative_path(data_path, DOCS_SAMPLES_CONTENT))
print("Docs: %d" % len(samples_content))

def get_content_for(index, samples_content, field='kps-normalized'):
    return samples_content[index][field]

print(get_content_for(docs_sample_a[0], samples_content, field='tokens'))
print(get_content_for(docs_sample_a[0], samples_content, field='content'))

In [32]:
from scipy.spatial.distance import cosine as cosine_distance

p = np.array([1, 2, 3])
q = np.array([0, 0, 3])
print(np.linalg.norm(p/np.sum(p) - q/np.sum(q)))
print(np.linalg.norm(p - q))
print(cosine_distance(p, q))
print(1.0 - np.dot(p, q)/(np.linalg.norm(p)*np.linalg.norm(q)))
print(cosine_distance(p/np.sum(p), q/np.sum(q)))

0.6236095644623235
2.23606797749979
0.1982162742627268
0.1982162742627268
0.19821627426272692


In [1]:
>>> from gensim.test.utils import common_texts
>>> from gensim.models.doc2vec import Doc2Vec, TaggedDocument
>>>
>>> documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
>>> model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)

In [7]:
common_texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]

In [6]:
[TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]

[TaggedDocument(words=['human', 'interface', 'computer'], tags=[0]),
 TaggedDocument(words=['survey', 'user', 'computer', 'system', 'response', 'time'], tags=[1]),
 TaggedDocument(words=['eps', 'user', 'interface', 'system'], tags=[2]),
 TaggedDocument(words=['system', 'human', 'system', 'eps'], tags=[3]),
 TaggedDocument(words=['user', 'response', 'time'], tags=[4]),
 TaggedDocument(words=['trees'], tags=[5]),
 TaggedDocument(words=['graph', 'trees'], tags=[6]),
 TaggedDocument(words=['graph', 'minors', 'trees'], tags=[7]),
 TaggedDocument(words=['graph', 'minors', 'survey'], tags=[8])]

In [22]:
>>> from gensim.models import LdaModel
>>> from gensim.test.utils import common_texts
>>> from gensim.corpora.dictionary import Dictionary
>>>
>>> # Create a corpus from a list of texts
>>> common_dictionary = Dictionary(common_texts)
>>> common_corpus = [common_dictionary.doc2bow(text) for text in common_texts]
>>>
>>> # Train the model on the corpus.
>>> lda = LdaModel(common_corpus, num_topics=10)


>>> # Create a new corpus, made of previously unseen documents.
>>> other_texts = [
...     ['computer', 'time', 'graph'],
...     ['survey', 'response', 'eps'],
...     ['human', 'system', 'computer']
... ]
>>> other_corpus = [common_dictionary.doc2bow(text) for text in other_texts]
>>>

In [24]:
unseen_doc = other_corpus[0]
vector = lda[other_corpus]

In [28]:
print(vector[1])

[(0, 0.025012165), (1, 0.025000004), (2, 0.025000004), (3, 0.025000008), (4, 0.5250005), (5, 0.025000004), (6, 0.025000008), (7, 0.025000004), (8, 0.025000008), (9, 0.2749873)]
